--[[
  config/defaults.lua — shipped defaults (CLAUDE.md "Config-Defaults" section).

  Do not edit this file to configure the mod. Instead create
    Scripts/config/user.lua        (return a table with overrides), or
    <mod root>/config/config.lua   (same format)
  Both are deep-merged over these defaults by config/loader.lua.

  The `api` section holds engine path candidates. Entries marked
  TODO(VERIFY) are hypotheses that get probed at runtime and fail soft;
  they must be confirmed against a Palworld 1.0 CXXHeaderDump / Live View
  before the dependent feature activates (see research/notes/verified-hooks.md).
]]

return {
  enabled = true,
  log_level = "info", -- debug | info | warn | error

  craft = {
    enabled = true,
    scope = "current_base", -- "all_guild_bases" is prepared but NOT implemented in v1
    refresh_interval_sec = 0.5,
    include_player_inventory = true,
    include_storage_containers = true,
    include_guild_chest = true,
    prefer_consume_order = "player_first", -- or "storage_first"
    exclude_class_substrings = {
      -- class-name substrings excluded from container discovery,
      -- e.g. "Personal", "Locker", "PalBox" (fill after dump review)
    },
    -- Containers whose base can't be located are excluded so we never pull
    -- from another base's chests (scope = current_base guarantee).
    include_unlocatable_containers = false,
    -- "vanilla_fallback": we consume ONLY when vanilla's own consume
    --   observably failed -> structurally no double-consume (default, safe).
    -- "replace": assumes the verified hook can fully suppress the vanilla
    --   consume path; only switch after in-game verification.
    consume_mode = "vanilla_fallback",
    -- Last-resort consume via direct StackCount property writes. Unsafe
    -- (bypasses game-side bookkeeping); keep false unless verified.
    allow_property_write_consume = false,
  },

  weight = {
    enabled = true,
    infinite_max_weight = 1000000,
    poll_interval_sec = 0.25,
    restore_on_leave = true,
    -- Ownership checks need group-id APIs. In singleplayer every base is
    -- the player's, so assuming ownership when unverified is safe there.
    -- Set false to hard-require a verified guild match (multiplayer).
    assume_own_base_when_unverified = true,
    base_radius_margin = 1.0, -- multiplier on AreaRange for inside-base checks
    base_rescan_interval_sec = 5.0,
  },

  debug = {
    dump_apis_on_init = false, -- run the API discovery dump once the game is ready
    dump_key = "F6",           -- in-game key to run the dump on demand; false disables
    log_index_summary = false, -- STEP 4 log-only mode: periodically log storage index totals
    index_summary_interval_sec = 5.0,
  },

  api = {
    weight = {
      -- Hook whose return value is the player's max carry weight.
      -- First candidate that registers wins.
      max_weight_hooks = {
        -- TODO(VERIFY): EA-era community mods hooked this; confirm for 1.0.
        "/Script/Pal.PalPlayerInventoryData:GetMaxInventoryWeight",
      },
    },

    base = {
      -- VERIFIED (community, BetterBaseRange mod): class exists and
      -- NotifyOnNewObject fires for it; AreaRange is a float property.
      base_camp_model_class = "/Script/Pal.PalBaseCampModel",
      short_class = "PalBaseCampModel",
      area_range_property = "AreaRange",
      default_area_range = 2000.0, -- community-observed fallback when unset
      -- TODO(VERIFY): where the camp's world position lives on the model.
      transform_properties = { "Transform" },
      transform_getters = { "GetTransform", "GetBaseCampTransform" },
      -- TODO(VERIFY): guild/group ownership fields.
      group_id_properties = { "GroupIdBelongTo", "OwnerGroupId" },
      group_id_getters = { "GetGroupIdBelongTo" },
      player_state_getters = { "GetPlayerState" },
      player_group_getters = { "GetGroupId" },
      player_group_properties = { "GroupId" },
    },

    craft = {
      -- TODO(VERIFY): both hooks are REQUIRED for F1 and intentionally nil.
      -- F1 soft-disables until they are filled from a 1.0 dump
      -- (see research/notes/verified-hooks.md for the workflow).
      count_hook = nil,   -- e.g. "/Script/Pal.<CraftComponent>:GetMaterialNum"
      consume_hook = nil, -- e.g. "/Script/Pal.<CraftComponent>:ConsumeMaterials"
      workbench_open_hook = nil, -- optional: craft UI open/close context

      -- Container discovery: FindAllOf over these short class names.
      -- TODO(VERIFY): candidates only; refine via the API dump (F6).
      container_model_classes = {
        "PalMapObjectItemContainerModel",
      },
      container_getters = { "GetItemContainer", "GetContainer" },
      container_properties = { "ItemContainer", "Container" },
      container_transform_properties = { "Transform" },
      container_transform_getters = { "GetTransform" },

      -- Player inventory containers relevant for crafting.
      -- TODO(VERIFY): which containers vanilla craft actually reads.
      inventory_data_getters = { "GetInventoryData" },
      inventory_data_properties = { "InventoryData" },
      player_container_getters = { "GetCommonContainer" },
      player_container_properties = { "CommonContainer", "Inventories" },

      -- Slot access on UPalItemContainer-ish objects. TODO(VERIFY).
      slot_num_getters = { "GetSlotNum", "GetSlotCount" },
      slot_getters = { "Get", "GetSlot" },
      slot_item_id_getters = { "GetItemId" },
      slot_item_id_properties = { "ItemId" },
      slot_stack_getters = { "GetStackCount", "GetNum" },
      slot_stack_properties = { "StackCount", "Num" },

      -- Item removal candidates, probed in order. Container-level ops get
      -- (slot_index, count); slot-level ops get (count). TODO(VERIFY).
      container_remove_ops = { "RemoveItemAt", "RemoveItemByIndex" },
      slot_remove_ops = { "RemoveItem", "DecreaseStackCount" },
      -- Refund candidates (best-effort rollback). TODO(VERIFY).
      container_add_ops = { "AddItem", "RequestAddItem" },
    },
  },
}
